[package]
name = "in-video-veritas"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#mmal-sys = "0"
tokio = "1"
tracing = "0.1"
rascam = "0"